 
 <!-- Añadir comentarios -->
 <form action="index.php?controller=comentarios&action=insert" method="post">
        <div class="form-group">
                <label for="exampleTextarea">Añadir comentario</label>
                <textarea class="form-control" id="exampleTextarea" name="mensaje" rows="3"></textarea>
        </div>

        <button type="submit" class="btn btn-secondary" name="insert">Enviar</button>

</form> <!-- Fin añadir comentarios -->