<!DOCTYPE html>
<html lang="en">

<head>
    <title>Torneos</title>
    <?php include 'head_view.html';?>
</head>

<body>

    
<?php include 'menu_view.phtml';?>

    <div class="container">


<h2>comentarios</h2>

    <div class="row">
        <div class="col-6">



              <table class="table table-bordered">
    <thead>
      <tr>
        <th>Comentarios del partido</th>
        <th class="textoCentrado">Eliminar</th>
       
      </tr>
    </thead>
    <tbody>
    <?php
                foreach ($datos as $dato) {
                     echo "
                     <tr>
                     <td>{$dato['mensaje']}
                     </td>

                     <td class='textoCentrado'>
                     <a href=index.php?controller=comentarios&action=delete&id={$dato['id_comentario']}><i class='fas fa-trash-alt'></i></a>
                    </td>
                     
                   </tr>";
                   
                    }
            ?>
     
    </tbody>
  </table>
            <!-- Añadir comentarios -->
  <form action="index.php?controller=comentarios&action=insert" method="post">
        <div class="form-group">
            <label for="exampleTextarea">Añadir comentario</label>
            <textarea class="form-control" id="exampleTextarea" name="mensaje" rows="3"></textarea>
        </div>
            
        <button type="submit" class="btn btn-primary" name="insert" >Enviar</button>
           
        </form>
        <!-- Fin añadir comentarios -->
        <a href='index.php?controller=comentarios&action=finalizarPartido'>Borrar todos los mensajes</a>
        </div>

        <div class="col-6">

        <h3>Información de partido</h3>
        <h4 id="local">Equipo Local</h4> <h4 id="verGolLocal">0</h4>
       <h4 id="visitante">Equipo Visitante</h4>  <h4 id="verGolVisitante">0</h4>

       <h3>Creación de partido</h3>




       <div class="form-group">
             <label>Equipo local:</label>
            <select id="id_equipoLocal" name="id_equipoLocal">
                <option value="Mallorca">Mallorca </option>
                <option value="Menorca">Menorca </option>
                <option value="Ibiza">Ibiza </option>
                <option value="Formentera">Formentera </option>
            </select>
        </div>
            

    <div class="form-group">
             <label >Equipo visitante:</label>
            <select id="id_equipoVisitante" name="id_equipoVisitante">
                <option value="Mallorca">Mallorca </option>
                <option value="Menorca">Menorca </option>
                <option value="Ibiza">Ibiza </option>
                <option value="Formentera">Formentera </option>
            </select><br><br>
            
            <button onclick="crearPartido()">Crear partido</button>
           
                  </div>
                  
                  <button onclick="añadirGolLocal()">Añadir gol local</button>
                  <button onclick="eliminarGolLocal()">Eliminar gol Local</button>
                  <button onclick="añadirGolVisitante()">Añadir gol visitante</button>
                  <button onclick="eliminarGolVisitante()">Eliminar gol visitante</button>
                  

<script>
//Variables globales
var golVisitante = 0;
var golLocal = 0 ;


function crearPartido(){
    
    var seleccionadoVisitante = document.getElementById('id_equipoVisitante').value;
    document.getElementById("visitante").innerHTML ="Equipo visitante "+ seleccionadoVisitante; 

    var seleccionadoLocal = document.getElementById('id_equipoLocal').value;
    document.getElementById("local").innerHTML ="Equipo local "+ seleccionadoLocal; 
}


function añadirGolVisitante(){
    golVisitante = golVisitante + 1 ;
    document.getElementById("verGolVisitante").innerHTML = golVisitante; 

}

function eliminarGolVisitante(){
    golVisitante = golVisitante - 1 ;
    document.getElementById("verGolVisitante").innerHTML = golVisitante; 

}

function añadirGolLocal(){
    golLocal = golLocal + 1 ;
    document.getElementById("verGolLocal").innerHTML = golLocal; 

}
function eliminarGolLocal(){
    golLocal = golLocal - 1 ;
    document.getElementById("verGolLocal").innerHTML = golLocal; 

}

</script>

        <h3>Insetar goles</h3>
        <h4>Equipo local</h4> <h4>puntos local</h4>
        <h4>Equipo visitante</h4>  <h4>puntos visitante</h4>

        </div>


    </div>
 </div>
</body>

</html>