<!DOCTYPE html>
<html lang="en">

<head>
    <title>Torneos</title>
    <?php include 'head_view.html';?>
</head>

<body>


    <?php include 'menu_view.phtml';?>

    <div class="container">


        <h2>Comentarios</h2>

        <div class="row">
            <div class="col-6">

                <?php if (isset ($_SESSION['usuario']))
                    { echo " <a style='
                        float:  right;
                        ' href='index.php?controller=comentarios&action=finalizarPartido'>Borrar todos los mensajes</a>"; 
                    } 
                ?>

                <div class="table-responsive-sm">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Comentarios del partido</th>
                                <?php if (isset ($_SESSION['usuario']))
                                { echo "
                                 <th class='textoCentrado'>Eliminar</th> ";
                                 } ?>

                            </tr>
                        </thead>
                        <tbody>
                            <?php
                                foreach ($datos as $dato) {

                                    if (isset ($_SESSION['usuario'])) {  
                                    echo "
                                    <tr>
                                        <td>{$dato['mensaje']}</td>

                                        
                                        <td class='textoCentrado'>
                                            <a href=index.php?controller=comentarios&action=delete&id={$dato['id_comentario']}><i class='fas fa-trash-alt'></i></a>
                                        </td>
                                    
                                    </tr>";

                                }else{
                                    echo"
                                    <tr>
                                        <td>{$dato['mensaje']}</td>
                                    </tr>
                                    ";
                                }
                                
                                }
                            ?>

                        </tbody>
                    </table>
                </div>


                <?php if (isset ($_SESSION['usuario'])) { include 'añadirComentario_view.phtml'; } ?>


            </div>

            <div class="col-6">

                <div>
                    <h3>Información de partido</h3>
                    <?php
                        foreach ($datosPartidos as $datosPartido) {
                            if($datosPartido['equipo_local'] == $datosPartido['id_equipo']){
                                echo "<h4>E. Local {$datosPartido['nombre']} - {$datosPartido['goles_local']} Puntos {$datosPartido['puntos']}</h4>";
                            }else{
                                echo "<h4>E. Visitante {$datosPartido['nombre']} - {$datosPartido['goles_visitante']} Puntos {$datosPartido['puntos']}</h4>";
                            };
                        }
                    ?>
                        <br>
                </div>

                <div>
                    <?php if (isset ($_SESSION['usuario'])) { include 'crearPartido_view.phtml'; } ?>

                </div>

                <div>
                    <?php if (isset ($_SESSION['usuario'])) { include 'insertarGoles_view.phtml'; } ?>

                </div>

                


            </div>


        </div>


    </div>
    </div>
</body>

</html>