<!DOCTYPE html>
<html lang="en">

<head>
  <title>Clasificación</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+"
    crossorigin="anonymous"></script>


</head>

<body>

  <?php include 'menu_view.html';?>


  <div class="container">

    <h2>Clasificación equipos</h2>


    <div class="row">
      <div class="col-8 table-responsive">

        <table class="table table-bordered">
          <thead>
            <tr>
              <th>Nombre
                <a href="index.php?controller=equipos&action=ordNombreAsc">
                  <i class="fas fa-arrow-up"></i>
                </a>
                <a href="index.php?controller=equipos&action=ordNombreDesc">
                  <i class="fas fa-arrow-down"></i>
                </a>
              </th>
              <th>Puntos
                <a href="index.php?controller=equipos&action=ordPuntosDesc">
                  <i class="fas fa-arrow-down"></i>
                </a>
                <a href="index.php?controller=equipos&action=ordPuntosAsc">
                  <i class="fas fa-arrow-up"></i>
                </a>
              </th>
              <th>Eliminar</th>

            </tr>
          </thead>
          <tbody>
            <?php
                foreach ($datos as $dato) {
                     echo "
                     <tr>
                     <td>{$dato['nombre']}
                     </td>

                     <td>
                     {$dato['puntos']}
                     </td>


                     <td>
                     <a href=\"index.php?controller=equipos&action=delete&id={$dato['id_equipo']}\">X</a>
                     </td>
                     
                   </tr>";
                   
                    }
            ?>

          </tbody>
        </table>

      </div>




      <div class="col-4">

        <!-- Button to Open the Modal -->
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
          Agregar equipo
        </button>

        <!-- The Modal -->
        <div class="modal fade" id="myModal">
          <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">

              <!-- Modal Header -->
              <div class="modal-header">
                <h4 class="modal-title">Introduce los datos del nuevo equipo</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
              </div>

              <!-- Modal body -->
              <div class="modal-body">
                <form action="index.php?controller=equipos&action=insert" method="post">

                  <div class="form-group">
                    <label for="nombre">Nombre del equipo:</label>
                    <input type="text" name="nombre" value="">
                  </div>


                  <button type="submit" class="btn btn-success" name="insert">Guardar</button>

                </form>
              </div>



            </div>
          </div>
        </div>

      </div>
    </div>

  </div>

</body>

</html>