<h3>Insertar puntos</h3>



<?php
                                foreach ($datosPartidos as $datosPartido) {
                                   
                                        if($datosPartido['equipo_local'] == $datosPartido['id_equipo']){
                                           echo" 
                                           <form action='index.php?controller=comentarios&action=insertarPuntos' method='post'>
                                        <div class='form-group'>
                                            <label for='puntoLocal'>E. Local:</label>
                                           <input type='number' name='puntoLocal' value={$datosPartido['puntos']}> ";
                                        } else {
                                            echo" 
                                            <form action='index.php?controller=comentarios&action=insertarGoles' method='post'>
                                        <div class='form-group'>
                                            <label for='puntoVisitante'>E. Visitante:</label>
                                            <input type='number' name='puntoVisitante' value={$datosPartido['puntos']}> ";
                                        }
                                
                                                               
                                                               
                                }
                                
                            ?>

                            <br>

<button type="submit" class="btn btn-primary" name="insert">Guardar puntos</button>
<br>
</form>




