<!DOCTYPE html>
<html lang="en">

<head>
  <title>jugadores</title>
  <?php include 'head_view.html';?>
</head>

<body>

  <?php include 'menu_view.html';?>


  <div class="container">

    <h2>jugadores</h2>


    <div class="row">
      <div class="col-8 table-responsive">

        <table class="table table-bordered">
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Apellidos</th>
              <th class='textoCentrado'>Dorsal</th>
              <th>Email</th>
              <th class='textoCentrado'>Sexo</th>
              <th class='textoCentrado'>Equipo</th>
              <th class='textoCentrado'>Eliminar</th>

            </tr>
          </thead>
          <tbody>
            <?php
                foreach ($datos as $dato) {
                     echo "
                     <tr>
                     <td>{$dato['nombre']}
                     </td>

                     <td>
                     {$dato['apellidos']}
                     </td>

                     <td class='textoCentrado'>
                     {$dato['dorsal']}
                     </td>

                     <td>
                     {$dato['email']}
                     </td>

                     <td class='textoCentrado'>
                     {$dato['sexo']}
                     </td>

                     <td class='textoCentrado'>
                     {$dato['id_equipo']}
                     </td>

                     <td class='textoCentrado'>
                     <a href=\"index.php?controller=jugadores&action=delete&id={$dato['id_jugador']}\"><i class='fas fa-trash-alt'></i></a>
                     </td>
                     
                   </tr>";
                   
                    }
            ?>

          </tbody>
        </table>

      </div>




      <div class="col-4">

        <!-- Button to Open the Modal -->
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
          Agregar jugador
        </button>

        <!-- The Modal -->
        <div class="modal fade" id="myModal">
          <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">

              <!-- Modal Header -->
              <div class="modal-header">
                <h4 class="modal-title">Introduce los datos del nuevo jugador</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
              </div>

              <!-- Modal body -->
              <div class="modal-body">
                <form action="index.php?controller=jugadores&action=insert" method="post">

                  <div class="form-group">
                    <label for="nombre">Nombre del jugador:</label>
                    <input type="text" name="nombre" value="">
                  </div>

                  <div class="form-group">
                    <label for="apellidos">Apellidos:</label>
                    <input type="text" name="apellidos" value="">
                  </div>

                  <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" name="email" value="">
                  </div>

                  <div class="form-group">
                    <label for="id_equipo">Equipo:</label>
                    <select name="id_equipo">

                      <option>Ninguno </option>
                      <option value=1>Equipo A </option>


                    </select>
                  </div>

                  <div class="form-group">
                    <label for="dorsal">Dorsal:</label>
                    <input type="number" name="dorsal" value="">
                  </div>

                  <div class="form-group">
                    <label for="sexo">Sexo:</label>

                    <div class="radio">
                      <label>
                        <input type="radio" name="sexo" value="M">Masculino</label>
                    </div>
                    <div class="radio">
                      <label>
                        <input type="radio" name="sexo" value="F">Femenino</label>
                    </div>
                  </div>



                  <button type="submit" class="btn btn-success" name="insert">Guardar</button>

                </form>
              </div>



            </div>
          </div>
        </div>

      </div>
    </div>

  </div>

</body>

</html>