<!-- Button to Open the Modal -->
<button type='button' class='btn btn-primary' data-toggle='modal' data-target='#myModal'>
        <i class='fas fa-trash-alt'></i>
         </button>
       
         <!-- The Modal -->
         <div class='modal fade' id='myModal'>
           <div class='modal-dialog modal-dialog-centered'>
             <div class='modal-content'>
             
               <!-- Modal Header -->
               <div class='modal-header'>
                 <h4 class='modal-title'>Aviso eliminación equipo</h4>
                 <button type='button' class='close' data-dismiss='modal'>&times;</button>
               </div>
               
               <!-- Modal body -->
               <div class='modal-body'>
                Estas apunto de eliminar para siempre un equipo, ¿Estas seguro?
               </div>
               
               <!-- Modal footer -->
               <div class='modal-footer'>
                 <button type='button' class='btn btn-success' data-dismiss='modal'>No, volver</button>
                 <button type='button' class='btn btn-danger' >Si, eliminar</button>
               </div>
               
             </div>
           </div>
         </div>