<!DOCTYPE html>
<html lang="en">

<head>
  <title>Torneos</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</head>

<body>

  <?php include 'menu_view.html';?>


  <div class="container">

    <h2>Torneos</h2>


    <div class="row">
      <div class="col-6">

         <table class="table table-bordered">
    <thead>
      <tr>
        <th>Listado de torneos</th>
       
      </tr>
    </thead>
    <tbody>
    <?php
                foreach ($datos as $dato) {
                     echo "
                     <tr>
                     <td>{$dato['nombre']}." .
                     "<a href=\"index.php?controller=torneos&action=delete&id={$dato['id_torneo']}\">Borrar</a><br/>
                     </td>
                     
                   </tr>";
                   
                    }
            ?>
     
    </tbody>
  </table>

      </div>




      <div class="col-6">

        <!-- Button to Open the Modal -->
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
          Agregar torneo
        </button>

        <!-- The Modal -->
        <div class="modal fade" id="myModal">
          <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">

              <!-- Modal Header -->
              <div class="modal-header">
                <h4 class="modal-title">Introduce los datos del nuevo deporte</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
              </div>

              <!-- Modal body -->
              <div class="modal-body">
                <form action="index.php?controller=torneos&action=insert" method="post">
                  <label for="nombre">Nombre del torneo:</label>
                  <input type="text" name="nombre" value="">
                  <br>

                  <button type="submit" class="btn btn-success" name="insert">Guardar</button>

                </form>
              </div>



            </div>
          </div>
        </div>

      </div>
    </div>

  </div>

</body>

</html>