<!DOCTYPE html>
<html lang="en">

<head>
  <title>Registro</title>
  <?php include 'head_view.html';?>
</head>

<body>

  <?php include 'menu_view.phtml';?>


  <div class="container">

    <h2>Registro</h2>


    <div class="row">
      <div class="col-6">

        <form action="index.php?controller=usuarios&action=insert" method="post">

          <div class="form-group">
            <label for="nombre">Nombre :</label>
            <input type="text" name="nombre" value="">
          </div>

          <div class="form-group">
            <label for="usuario">Usuario:</label>
            <input type="text" name="usuario" value="">
          </div>

          <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" name="password" value="">
          </div>

      
          <button type="submit" class="btn btn-success" name="insert">Guardar</button>

        </form>

      </div>
    </div>

  </div>

</body>

</html>